### ISSUE TITLE
Bug: Extendable Uri Resolver is not working

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/kotlin-client#27]
@nerfZael is fixing. @krisbitney can you please provide details here? Also please feel free to change title.

**Comment by krisbitney** [comment]
The Extendable URI Resolver isn't working. 

@nerfZael is working on it here: https://github.com/polywrap/rust-client/pull/125

Jure's work depends on this PR: https://github.com/polywrap/rust-client/pull/123

**Comment by krisbitney** [comment]
This has been completed
