### ISSUE TITLE
Bug: FFI cannot write to callback interface

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/kotlin-client#28]
@namesty is fixing. @krisbitney can you please provide details here? Also please feel free to change title.

**Comment by krisbitney** [comment]
Uniffi doesn't support the case where a foreign object is passed back from Rust into the foreign language.

In our case, Rust defines "callback interfaces" `FfiInvoker` and `FfiAbortHandler`. They are meant to be implemented in a foreign language (e.g. Kotlin) and passed into Rust. But in our case, we are trying to pass them from Rust into Kotlin. In a plugin invocation, `FfiAbortHandler` is implemented in Kotlin and passed into `client.invoke` as an argument, and then Rust calls `plugin.invoke` on a Kotlin plugin and tries to pass it as an argument. 

The lack of support for this kind of behavior is not documented, so we weren't aware of the limitation until we encountered an exception.

**Comment by krisbitney** [comment]
Update: as a workaround, we are currently using Rust default config with Rust plugins

**Comment by krisbitney** [comment]
A minimal reproduction of the error is demonstrated in https://github.com/polywrap/kotlin-client/pull/40
