### ISSUE TITLE
Add CI / CD

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/kotlin-client#29]
- [x] CI
- [x] CD

Example CI / CD Pipelines:
https://github.com/polywrap/rust-client/tree/main/.github/workflows
https://github.com/polywrap/javascript-client/tree/origin-dev/.github/workflows
https://github.com/polywrap/python-client/tree/main/.github/workflows

**Comment by krisbitney** [comment]
See https://github.com/polywrap/kotlin-client/issues/3

**Comment by krisbitney** [comment]
completed in https://github.com/polywrap/kotlin-client/pull/35
